### ISSUE TITLE
Class "DeepL\Translator" not found

### ISSUE THREAD

**Issue by Hobokens** [thieleundklose/autotranslate#7]
TYPO3 12.4.7

After adding my free deepL authentification key in the site configuration and saving the file I get the error above. I have the same problem with a payed key.

`"DeepL\Translator" not found | Error thrown in file /aaa/bbb/ccc/bk/www/live/typo3conf/ext/autotranslate/Configuration/SiteConfiguration/Overrides/sites.php in line 129.`

**Comment by mikezimmer-tuk** [comment]
Hello, unfortunately there is a problem that the autoload information is not processed correctly when installing via TYPO3 Ter. This bug should actually have already been fixed by TYPO3. I am therefore closing the issue. If you still have problems, don't hesitate to write to us again. Best regards, Mike
